/**
 * TranscriptExporter
 * Serializes terminal command logs and outputs into downloadable Markdown transcripts,
 * HTML archives, and raw ASCII session summaries.
 */

export class TranscriptExporter {
  /**
   * Export session logs to Markdown format
   */
  exportToMarkdown(session = {}, history = []) {
    const levelId = session.levelId || '01';
    const timestamp = session.timestamp ? new Date(session.timestamp).toISOString() : new Date().toISOString();
    const duration = session.durationSeconds || 0;
    const moves = session.moveCount || 0;

    let md = `# GitHero Tactical Terminal Transcript\n\n`;
    md += `**Sector**: Sector ${levelId}\n`;
    md += `**Date**: ${timestamp}\n`;
    md += `**Duration**: ${duration}s | **Moves**: ${moves}\n\n`;
    md += `## Command Execution History\n\n`;

    if (!history || history.length === 0) {
      md += `*No commands executed during this session.*\n`;
    } else {
      history.forEach((entry, idx) => {
        md += `### ${idx + 1}. \`${entry.command}\`\n\n`;
        md += `\`\`\`bash\n$ ${entry.command}\n${entry.output || ''}\n\`\`\`\n\n`;
      });
    }

    md += `---\n*Generated by GitHero Terminal System*\n`;
    return md;
  }

  /**
   * Trigger browser file download
   */
  triggerDownload(content, filename = 'terminal_transcript.md', mimeType = 'text/markdown') {
    if (typeof window === 'undefined' || typeof document === 'undefined') return;

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}

export const transcriptExporter = new TranscriptExporter();
